CREATE TABLE listings(
	unique_identifier INT NOT NULL,
	listing_amount INT ,
	amount_funded INT ,
	lender_yield FLOAT ,
	borrower_apr FLOAT ,
	listing_term INT ,
	listing_monthly_payment FLOAT,
	income_range INT ,
	income_range_description VARCHAR(50) ,
	stated_monthly_income FLOAT,
	employment_status INT,
	employment_status_description VARCHAR(25) ,
	occupation VARCHAR(50) ,
	months_employed INT ,
	borrower_state_num INT,
	borrower_state VARCHAR(2),
	borrower_city VARCHAR(25),
	prior_prosper_loans INT ,
	prior_prosper_loans_principal_borrowed FLOAT ,
	prior_prosper_loans_principal_outstanding FLOAT,
	prior_prosper_loans_balance_outstanding INT ,
	prior_prosper_loans_cycles_billed INT ,
	prior_prosper_loans_ontime_payments INT ,
	prior_prosper_loans_late_cycles INT ,
	prior_prosper_loan_earliest_pay_off INT ,
	lender_indicator INT ,
	group_indicator BOOLEAN,
	Fico_rating INT,
	TUFicoRange VARCHAR(25) ,
	dti_wprosper_loan FLOAT ,
	CoBorrowerApplication BOOLEAN ,
	CombinedDtiwProsperLoan FLOAT ,
	CombinedStatedMonthlyIncome FLOAT,
	rating_num INT,
	prosper_rating VARCHAR(5),
	PRIMARY KEY(unique_identifier)
);
